spring:
  data:
    mongodb:
      # 默认数据源
      uri: ${MONGODB_DEFAULT_URL:mongodb://root:root@47.97.106.38:27017/admin}
      # 开启多数据源分片
      enable-sharding: true
      # 多数据源配置
      datasource:
        datasource1:
          order: 1
          uri: ${MONGODB_DEFAULT_URL:mongodb://root:root@47.97.106.38:27017/admin}
        datasource2:
          order: 2
          uri: ${MONGODB_DEFAULT_URL:mongodb://omsuat:qOwtYub!RQzm@114.67.212.174:27017/admin}
  application:
    name: demo-enhance-mongo

server:
  port: 10000