spring:
  application:
    name: enhance-data-source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://wenpan-host:3306/stone_project?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:wenpan}

    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://wenpan-host:3306/product_master?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
          username: ${SPRING_DATASOURCE_USERNAME:root}
          password: ${SPRING_DATASOURCE_PASSWORD:wenpan}

        slave:
          driver-class-name: com.mysql.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://wenpan-host:3306/product_slave?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
          username: ${SPRING_DATASOURCE_USERNAME:root}
          password: ${SPRING_DATASOURCE_PASSWORD:wenpan}
      hikari:
        min-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:10}
        max-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:90}
        connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

# 调整日志级别
logging:
  level:
    org.enhance.datasource.demo.mapper: debug
